# Generated by Django 3.0.6 on 2020-05-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(choices=[('cl', 'UEFA Champions League'), ('el', 'UEFA Europa League')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('fbrefid', models.CharField(max_length=10)),
            ],
        ),
    ]
