# Generated by Django 3.0.6 on 2020-05-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winprob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tie',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='winprob.Team'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='winprob.Team'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='winning_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_team', to='winprob.Team'),
        ),
    ]
