# Generated by Django 3.0.6 on 2020-05-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winprob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_slug',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
