# Generated by Django 3.0.6 on 2020-06-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winprob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tie',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
