# Generated by Django 3.0.6 on 2020-05-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winprob', '0002_team_team_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_slug',
            new_name='slug',
        ),
    ]
