# Generated by Django 3.0.6 on 2020-06-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winprob', '0002_auto_20200601_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tie',
            name='result',
            field=models.CharField(max_length=200),
        ),
    ]
