# Generated by Django 3.0.6 on 2020-05-28 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winprob', '0003_auto_20200527_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winprob.Country'),
        ),
    ]
