# Generated by Django 3.0.6 on 2020-06-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winprob', '0003_auto_20200601_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='ag',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='chgpredictedprobt1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='error',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='likelihood',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='predictedprobt1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='proba1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='probd1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='probh1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='sqerror',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='t1win',
            field=models.BooleanField(null=True),
        ),
    ]
