# Generated by Django 3.0.6 on 2020-06-01 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winprob', '0004_auto_20200601_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='tie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='winprob.Tie'),
        ),
    ]
