# Generated by Django 3.0.7 on 2020-06-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winprob', '0006_remove_prediction_tie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tie',
            name='excitement',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tie',
            name='minprob_winner',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tie',
            name='tension',
            field=models.FloatField(null=True),
        ),
    ]
