# Generated by Django 3.0.7 on 2020-06-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winprob', '0007_auto_20200608_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='shortnames',
            field=models.TextField(null=True),
        ),
    ]
