# Generated by Django 3.0.7 on 2020-06-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winprob', '0008_team_shortnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='tie',
            name='aggscore_t1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tie',
            name='aggscore_t2',
            field=models.IntegerField(null=True),
        ),
    ]
