# Generated by Django 3.0.7 on 2021-04-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winprob', '0009_auto_20200609_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediction',
            old_name='ag',
            new_name='is_away_goal',
        ),
        migrations.RenameField(
            model_name='tie',
            old_name='minprob_winner',
            new_name='comeback',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='awaygoalst1diff',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='goalst1diff',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='proba1',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='probd1',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='probh1',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='redcardst1diff',
        ),
        migrations.AddField(
            model_name='prediction',
            name='is_goal',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='is_red_card',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='playerst1',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediction',
            name='playerst2',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tie',
            name='competition_code',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tie',
            name='dates',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tie',
            name='stagecode',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tie',
            name='competition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tie',
            name='stage',
            field=models.CharField(max_length=200),
        ),
    ]
