# Generated by Django 3.0.7 on 2021-04-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winprob', '0012_prediction_actualminute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
