# Generated by Django 3.2 on 2021-04-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winprob', '0013_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tie',
            name='in_progress_halfway',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
