# Generated by Django 3.2 on 2021-04-29 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winprob', '0015_auto_20210429_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='tie',
            name='season_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season', to='winprob.season'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='season',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
