---
title: "Part 1: Getting results from goals"
output:
  github_document:
    html_preview: false
---

```{r}
library(tidyverse)
```

```{r}
library(broom)
```


```{r}
EQUIPOS = read_delim('raw/teamcrosswalk.psv', delim = '|')
```

```{r}
View(EQUIPOS)
```

```{r}
GOLES = read_delim('raw/goles - liga de campeones - Sheet1.tsv', delim = '\t')
```

```{r}
goles = GOLES %>% 
  fill(season, round, tie, game) %>%
  separate(tie, c('t1','t2'), sep = '-', remove = FALSE) %>% 
  left_join(EQUIPOS %>% select(t1 = teamcode, t1full = fullteam), by = 't1') %>% 
  left_join(EQUIPOS %>% select(t2 = teamcode, t2full = fullteam), by = 't2')
```


```{r}
head(goles)
```

```{r}
tail(goles)
```

```{r}
sum_goals = function(part) {
  # Gets the goals and away goals for a part of a game.
  # A "part" is regular or extra time.
  t1ag = part %>% filter(game == 2) %>% filter(!is.na(away)) %>% nrow()
  t2ag = part %>% filter(game == 1) %>% filter(!is.na(away)) %>% nrow()
  
  t1g = part %>% filter(game == 1) %>% filter(is.na(away)) %>% nrow() + t1ag
  t2g = part %>% filter(game == 2) %>% filter(is.na(away)) %>% nrow() + t2ag
  
  data.frame(t1g, t2g, t1ag, t2ag)
}
```

```{r}
get_tie_result = function(goals) {
    winner = NULL
    pk = agr = aet = FALSE
    result = ""
    
    t1 = goals %>% select(t1) %>% distinct() %>% first()
    t2 = goals %>% select(t2) %>% distinct() %>% first()
    
    reg = goals %>%
      filter(minute != 'pk') %>%
      filter(is.na(extra)) %>% 
      filter(!is.na(minute))

    et = goals %>%
      filter(minute != 'pk') %>%
      filter(!is.na(extra)) %>% 
      filter(!is.na(minute))

    pkg = goals %>% filter(minute == 'pk')

    # goals and away goals in regulation
    reg_goals = sum_goals(reg)
    t1g = reg_goals$t1g
    t2g = reg_goals$t2g
    t1ag = reg_goals$t1ag
    t2ag = reg_goals$t2ag

    # goals and away goals in extra time
    et_goals = sum_goals(et)
    t1etg = et_goals$t1g
    t2etg = et_goals$t2g
    t1etag = et_goals$t1ag
    t2etag = et_goals$t2ag

    # pk shootout result
    t1pkwin = pkg %>%
      filter(away == 'a') %>%
      nrow() %>%
      as.logical()
    
    if ( (t1g+t1etg) != (t2g+t2etg) ) {
      # if goal sums differ, outright win
      winner = case_when(
        ((t1g+t1etg) > (t2g+t2etg)) ~ t1,
        TRUE ~ t2
      )
    } else if ( (t1ag+t1etag) != (t2ag+t2etag) ) {
      # if away goal sums differ, away goals win
      winner = case_when(
        ((t1ag+t1etag) > (t2ag+t2etag)) ~ t1,
        TRUE ~ t2
      )
      agr = TRUE
    } else {
      winner = case_when(
        t1pkwin ~ t1,
        TRUE ~ t2
      )
      pk = TRUE
    }

    # if goals in regulation are tied
    # and away goals in regulation are tied
    # this went to extra time
    if ((t1g == t2g) & (t1ag == t2ag)) {
        aet = TRUE
    }
    
    winnerfull = case_when(
      winner == t1 ~ goals %>% select(t1full) %>%  distinct() %>% first(),
      TRUE ~ goals %>% select(t2full) %>%  distinct() %>% first()
    )

    # a string summarizing the result
    result = str_c(
        goals %>% select(t1full) %>% distinct(), ' (',
        t1g+t1etg, '-',
        t2g+t2etg,
        case_when(aet ~ ' aet) ', TRUE ~ ') '),
        goals %>% select(t2full) %>% distinct(),
        case_when(
          pk ~ str_c(', ', winnerfull, ' won on penalties'),
          agr ~ str_c(', ', winnerfull, ' won on away goals'),
          TRUE ~ ''
        )
    )

    data.frame(winner=winner, pk=pk, agr=agr, aet=aet, result=result)
}
```

```{r warning=FALSE}
results = goles %>% 
  group_by(season, round, tie) %>% 
  do(get_tie_result(.))
```


