---
title: "R Notebook"
output:
  github_document:
    html_preview: false
---

```{r}
library(readxl)
library(tidyverse)
```

```{r}
ODDS = read_excel('raw/oddsportal-odds.xlsx', col_names = FALSE)
```

```{r}
odds = ODDS %>%
  mutate(tmp = coalesce(X__2, X__1)) %>% 
  mutate(season = case_when(
    tmp == X__2 ~ NA_character_,
    TRUE ~ tmp
  )) %>% 
  mutate(season = str_sub(season, start = 8, end = 11)) %>% 
  fill(season, .direction = 'down') %>% 
  drop_na(2) %>% 
  select(2,4,5,6,season)

names(odds) = c('tie','oddshome','oddsdraw','oddsaway','season')
```

```{r}
odds = odds %>% 
  separate(tie, into = c('hometeam','awayteam'), sep = ' - ', remove = FALSE)
```

```{r}
head(odds)
```

```{r}
oddstopct = function(N) {
  if(N == '-') return(NA)
  n = as.numeric(N)
  final = case_when(
    n < 0 ~ -n / (-n + 100),
    TRUE ~ 100 / (n + 100)
  )
  final
}
```

```{r}
odds = odds %>% 
  mutate(
    pcthomeunadj = oddstopct(oddshome),
    pctdrawunadj = oddstopct(oddsdraw),
    pctawayunadj = oddstopct(oddsaway),
    impliedsum = pcthomeunadj + pctdrawunadj + pctawayunadj,
    pcthome = pcthomeunadj / impliedsum,
    pctdraw = pctdrawunadj / impliedsum,
    pctaway = pctawayunadj / impliedsum
  )
```

```{r}
results = read_csv('processed/results.csv')
```

```{r}
teams = read_delim('raw/teamcrosswalk.psv', delim = '|')
```

```{r}
twolegs = function(df) {
  t1 = df$t1[1]
  t2 = df$t2[1]
  tibble(
    game = c(1,2),
    hometeam = c(t1, t2),
    awayteam = c(t2, t1)
  )
}
```


```{r}
games.odds.xwalk = results %>% 
  select(season, tie) %>% 
  separate(tie, into = c('t1','t2'), sep = '-', remove = FALSE) %>% 
  group_by(season, round, tie) %>% 
  do(twolegs(.)) %>% 
  left_join(teams %>% select(hometeam = teamcode, hometeamfull = fullteam), by = 'hometeam') %>% 
  left_join(teams %>% select(awayteam = teamcode, awayteamfull = fullteam), by = 'awayteam') %>% 
  left_join(odds %>% select(season,hometeam,awayteam,pcthome,pctdraw,pctaway), by = c('season','hometeam','awayteam))
```

