---
title: "Plotting Champions League two-legged win probability"
output:
  md_document:
    variant: markdown_github
  html_notebook: default
---

```{r}
library(tidyverse)
```

```{r}
winprob = read_csv('analysis/winprob-model.csv')
```

```{r}
teamnames = read_delim('raw/teamcrosswalk.psv', delim = '|')
```

```{r}
results = read_csv('processed/results.csv')
```

```{r}
plot_winprob = function(slug) {
  pieces = str_split(slug, pattern = '\\|')
  y = pieces[[1]][1]
  r = pieces[[1]][2]
  t = pieces[[1]][3]
  t1 = str_split(t, pattern='-')[[1]][1]
  t2 = str_split(t, pattern='-')[[1]][2]
  t1full = teamnames %>% filter(teamcode == t1) %>% pull(fullteam)
  t2full = teamnames %>% filter(teamcode == t2) %>% pull(fullteam)
  t1code = teamnames %>% filter(teamcode == t1) %>% pull(shortcode)
  t2code = teamnames %>% filter(teamcode == t2) %>% pull(shortcode)
  result = results %>% 
    filter(season == y) %>% 
    filter(round == r) %>% 
    filter(tie == t) %>% 
    pull(result)
  title = str_c(
    result,'\n',
    y, ' ',
    case_when(
      r == 'first' ~ 'Round of 16',
      r == 'qtr' ~ 'Quarterfinal',
      r == 'semi' ~ 'Semifinal',
      TRUE ~ ''
    )
  )
  winprob %>% 
    filter(season == y) %>% 
    filter(round == r) %>% 
    filter(tie == t) %>% 
    gather(key = winprobmodel, value = winprob, neutral, pregameodds, pregameodds2) %>% 
    ggplot(aes(made_minute, winprob, color=winprobmodel)) +
    geom_line() +
    scale_y_continuous(
      limits = c(0,1),
      breaks = c(0.0,0.25,0.5,0.75,1.0),
      labels = c(
        str_c(t2code, '\n100%'),
        str_c(t2code, '\n75%'),
        '50%',
        str_c(t1code, '\n75%'),
        str_c(t1code, '\n100%')
      )
    ) +
    scale_x_continuous(
      breaks = c(0, 46, 92, 138, 184),
      labels = c('Gm. 1 start','Gm. 1 half','Gm. 1 end\nGm. 2 start','Gm. 2 half','End')
    ) +
    theme_minimal() +
    annotate('text', x = 1, y = 0.975, label = str_c('At ', t1full), size = 3, hjust = 0) +
    annotate('text', x = 93, y = 0.975, label = str_c('At ', t2full), size = 3, hjust = 0) +
    xlab("Minutes left") +
    ylab("") +
    ggtitle(title)
}
```

```{r}
plot_winprob('2008|first|arsenal-milan')
```


```{r}
for (i in 1:nrow(results)) {
  slug = str_c(
    results[i,]$season[1], '|',
    results[i,]$round[1], '|',
    results[i,]$tie[1]
  )
  p = plot_winprob(slug)
  ggsave(str_c('analysis/plots/',slug,'.pdf'), plot = p, width = 11, height = 8.5, units = "in")
}
```

