---
title: "Champions League two-legged win probability model"
output:
  md_document:
    variant: markdown_github
  html_notebook: default
---

```{r}
library(locfit)
library(tidyverse)
```

```{r}
results = read_csv('processed/results.csv')
```


```{r}
matrix  = read_csv('processed/minute-matrix.csv')
```

```{r}
head(matrix)
```

```{r}
tail(matrix)
```

```{r}
model.neutral = locfit(
  t1win ~ made_minute + t1goaldiff + t1awaygoaldiff,
  data = matrix,
  family = 'binomial'
)
```

```{r}
model.pregameodds = locfit(
  t1win ~ made_minute + t1goaldiff + t1awaygoaldiff + 
    pcthomeg1 + pcthomeg2,
  data = matrix,
  family = 'binomial'
)
```

```{r}
winprob = matrix %>% 
  mutate(
    neutral = predict(model.neutral, newdata = ., type = "response"),
    pregameodds = predict(model.pregameodds, newdata = ., type = "response")
  ) %>% 
  select(season, round, tie, t1win, made_minute, away, t1goaldiff, t1awaygoaldiff, neutral, pregameodds)
```


```{r}
errors = winprob %>% 
  mutate(
    errorN = t1win - neutral, errorO = t1win - pregameodds,
    sqrErrorN = errorN^2, sqrErrorO = errorO^2
  ) %>% 
  group_by(made_minute) %>% 
  summarise(
    count = n(),
    neutral = sqrt(mean(sqrErrorN)),
    pregameodds = sqrt(mean(sqrErrorO))
  )

errors %>% 
  select(-count) %>% 
  gather(key = method, value = rtMeanSqrError, neutral, pregameodds) %>% 
  ggplot() +
  geom_line(aes(x = made_minute, y = rtMeanSqrError, color = method)) +
  ggtitle('Root mean squared error by minute of tie') +
  scale_x_continuous(
    breaks = c(0, 46, 92, 138, 184, 216),
    labels = c('g1 start','g1 half','g1 end\ng2 start','g2 half','g2 end\net start','et end')
  ) +
  theme_minimal()
```

```{r}
proberrorN = winprob %>% 
  select(made_minute, pregameodds, t1win) %>% 
  mutate(probrange = cut_interval(pregameodds, 20)) %>% 
  group_by(probrange) %>% 
  summarise(actualprob = sum(t1win) / n()) %>% 
  mutate(
    probcut = probrange %>% 
      as.character() %>% 
      str_extract(",.*]") %>% 
      str_sub(start = 2, end = -2) %>% 
      as.numeric()
  )

proberrorO = winprob %>% 
  select(made_minute, neutral, t1win) %>% 
  mutate(probrange = cut_interval(neutral, 20)) %>% 
  group_by(probrange) %>% 
  summarise(actualprob = sum(t1win) / n()) %>% 
  mutate(
    probcut = probrange %>% 
      as.character() %>% 
      str_extract(",.*]") %>% 
      str_sub(start = 2, end = -2) %>% 
      as.numeric()
  )

proberrorN %>% 
  select(probcut, actualprob) %>% 
  left_join(
    proberrorO %>% 
      select(actualprob, probcut),
    by = 'probcut',
    suffix = c('.neutral','.pregameodds')
  ) %>% 
  gather(key = winprobtype, value = winprob, actualprob.neutral, actualprob.pregameodds) %>% 
  mutate(winprobtype = str_replace(winprobtype, 'actualprob.', '')) %>% 
  ggplot() +
  geom_line(aes(probcut, winprob, color = winprobtype)) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed")
```

```{r}
winprob %>% 
  group_by(season, round, tie, made_minute) %>%
  count() %>%
  filter(n > 1)
```

```{r}
winprob %>% 
  group_by(season, round, tie) %>% 
  mutate(wpdiff = abs(pregameodds - lag(pregameodds))) %>% 
  drop_na(away) %>% 
  arrange(-wpdiff) %>% 
  head(30) %>% 
  select(season, round, tie, made_minute, t1win, away, wpdiff)
```

```{r}
y = 2018
r = 'qtr'
t = 'barcelona-roma'

winprob %>% 
  filter(season == y) %>% 
  filter(round == r) %>% 
  filter(tie == t) %>% 
  gather(key = winprobmodel, value = winprob, neutral, pregameodds) %>% 
  ggplot(aes(made_minute, winprob, color=winprobmodel)) +
  geom_line() +
  scale_y_continuous(limits = c(0,1)) +
  scale_x_continuous(
    breaks = c(0, 46, 92, 138, 184),
    labels = c('g1 start','g1 half','g1 end\ng2 start','g2 half','end')
  ) +
  theme_minimal() +
  xlab("Minutes left") +
  ylab("Win probability")
```

```{r}
write_csv(winprob, 'analysis/winprob-model.csv', na = '')
```
