---
title: "R Notebook"
output: html_notebook
---

```{r}
library(locfit)
library(tidyverse)
```

```{r}
matrix  = read_csv('minute-matrix.csv')
```

```{r}
head(matrix)
```

```{r}
tail(matrix)
```

```{r}
model.simple = locfit(
  t1win ~ made_minute + t1goaldiff + t1awaygoaldiff,
  data = matrix,
  family = 'binomial'
)
```

```{r}
model.odds = locfit(
  t1win ~ made_minute + t1goaldiff + t1awaygoaldiff + 
    homewing1 + homewing2,
  data = matrix,
  family = 'binomial'
)
```

```{r}
model.odds2 = locfit(
  t1win ~ made_minute + t1goaldiff + t1awaygoaldiff + 
    awaywing1 + awaywing2,
  data = matrix,
  family = 'binomial'
)
```

```{r}
winprob = matrix %>% 
  mutate(
    neutral = predict(model.simple, newdata = ., type = "response"),
    odds = predict(model.odds, newdata = ., type = "response"),
    odds2 = predict(model.odds2, newdata = ., type = "response")
  ) %>% 
  select(season, round, tie, t1win, made_minute, neutral, odds, odds2)
```


```{r}
errors = winprob %>% 
  mutate(
    errorN = t1win - neutral, errorO = t1win - odds, errorO2 = t1win - odds2,
    sqrErrorN = errorN^2, sqrErrorO = errorO^2, sqrErrorO2 = errorO2^2
  ) %>% 
  group_by(made_minute) %>% 
  summarise(
    count = n(),
    rtmeanSqrErrorN = sqrt(mean(sqrErrorN)),
    rtmeanSqrErrorO = sqrt(mean(sqrErrorO)),
    rtmeanSqrErrorO2 = sqrt(mean(sqrErrorO2))
  )

errors %>% 
  select(-count) %>% 
  gather(key = errorType, value = rtMeanSqrError, rtmeanSqrErrorN, rtmeanSqrErrorO, rtmeanSqrErrorO2) %>% 
  ggplot() +
  geom_line(aes(x = made_minute, y = rtMeanSqrError, color = errorType))
```

```{r}
proberror = winprob %>% 
  select(made_minute, odds, t1win) %>% 
  mutate(probrange = cut_interval(odds, 20)) %>% 
  group_by(probrange) %>% 
  summarise(actualprob = sum(t1win) / n()) %>% 
  mutate(
    probcut = probrange %>% 
      as.character() %>% 
      str_extract(",.*]") %>% 
      str_sub(start = 2, end = -2) %>% 
      as.numeric()
  )

proberror %>% 
  ggplot() +
  geom_point(aes(probcut, actualprob)) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed")
```



```{r}
y = 2017
r = 'first'
t = 'psg-barcelona'

winprob %>% 
  filter(season == y) %>% 
  filter(round == r) %>% 
  filter(tie == t) %>% 
  gather(key = winprobmodel, value = winprob, neutral, odds) %>% 
  ggplot(aes(made_minute, winprob, color=winprobmodel)) +
  geom_line() +
  scale_y_continuous(limits = c(0,1)) +
  scale_x_continuous(
    breaks = c(0, 46, 92, 138, 184),
    labels = c('g1 start','g1 half','g1 end\ng2 start','g2 half','end')
  ) +
  theme_minimal() +
  xlab("Minutes left") +
  ylab("Win probability")
```

